### PR TITLE
Added pre/post task hooks

### PR DESCRIPTION
**Pull request by jstruebel**

### CODE REVIEW

**Comment by drybjed** [comment]
It seems that `stunnel4` was not started correctly after the test on Travis-CI. it might be an issue with the configuration. I'll check it out after getting back from holidays, in about a week.

**Comment by jstruebel** [comment]
No problem. It's a pretty simple change so hopefully it will be obvious if it broke anything.

**Comment by jstruebel** [comment]
I just ran into the issue that I had needed the pre/post hooks to resolve and discovered that it hadn't been merged into your master repo. I merged in the recent changes and it looks like it is all passing the tests now.

**Comment by jstruebel** [comment]
Since the tests are passing now, can this change be merged?

**Pull request merged**
